/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cosc457wiltondatabase.Main;

import javax.swing.JTable;

/**
 *
 * @author Sara
 */
public class Works_On_Table extends javax.swing.JFrame {

    /**
     * Creates new form Works_On_Table
     */
    public Works_On_Table() {
        initComponents();
        populateWorksOnTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        AssignTaskButton = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        employeePage6 = new javax.swing.JButton();
        officeButton6 = new javax.swing.JButton();
        PurchaseOrderButton6 = new javax.swing.JButton();
        WorksOnButton6 = new javax.swing.JButton();
        CustomerButton6 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1EmployeeTableShow2 = new javax.swing.JScrollPane();
        BacktoInsert2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(0, 102, 153));

        jLabel15.setFont(new java.awt.Font("Javanese Text", 1, 50)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CORPORATION");

        jLabel16.setFont(new java.awt.Font("Javanese Text", 1, 50)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("WILTON");

        jButton19.setBackground(new java.awt.Color(0, 102, 153));
        jButton19.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 51));
        jButton19.setText("Order Item");
        jButton19.setToolTipText("");
        jButton19.setBorder(null);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        AssignTaskButton.setBackground(new java.awt.Color(0, 102, 153));
        AssignTaskButton.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        AssignTaskButton.setForeground(new java.awt.Color(0, 0, 51));
        AssignTaskButton.setText("Assign Task");
        AssignTaskButton.setBorder(null);
        AssignTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTaskButtonActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(0, 102, 153));
        jButton21.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 0, 51));
        jButton21.setText("Sales Order");
        jButton21.setBorder(null);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        employeePage6.setBackground(new java.awt.Color(0, 102, 153));
        employeePage6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        employeePage6.setForeground(new java.awt.Color(0, 0, 51));
        employeePage6.setText("Employee");
        employeePage6.setBorder(null);
        employeePage6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePage6ActionPerformed(evt);
            }
        });

        officeButton6.setBackground(new java.awt.Color(0, 102, 153));
        officeButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        officeButton6.setForeground(new java.awt.Color(0, 0, 51));
        officeButton6.setText("Office");
        officeButton6.setBorder(null);
        officeButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeButton6ActionPerformed(evt);
            }
        });

        PurchaseOrderButton6.setBackground(new java.awt.Color(0, 102, 153));
        PurchaseOrderButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        PurchaseOrderButton6.setForeground(new java.awt.Color(0, 0, 51));
        PurchaseOrderButton6.setText("PO");
        PurchaseOrderButton6.setBorder(null);
        PurchaseOrderButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseOrderButton6ActionPerformed(evt);
            }
        });

        WorksOnButton6.setBackground(new java.awt.Color(0, 102, 153));
        WorksOnButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        WorksOnButton6.setForeground(new java.awt.Color(0, 0, 51));
        WorksOnButton6.setText("Works On");
        WorksOnButton6.setBorder(null);
        WorksOnButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorksOnButton6ActionPerformed(evt);
            }
        });

        CustomerButton6.setBackground(new java.awt.Color(0, 102, 153));
        CustomerButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        CustomerButton6.setForeground(new java.awt.Color(0, 0, 51));
        CustomerButton6.setText("Customer");
        CustomerButton6.setBorder(null);
        CustomerButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(employeePage6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AssignTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(officeButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PurchaseOrderButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorksOnButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel16)
                    .addContainerGap(739, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeePage6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(officeButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PurchaseOrderButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WorksOnButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel16)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BacktoInsert2.setBackground(new java.awt.Color(0, 102, 153));
        BacktoInsert2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        BacktoInsert2.setForeground(new java.awt.Color(255, 255, 255));
        BacktoInsert2.setText("Back to Insert");
        BacktoInsert2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BacktoInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoInsert2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jScrollPane1EmployeeTableShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BacktoInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1EmployeeTableShow2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(BacktoInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("Works On Table");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Order_Item orderitem = new Order_Item();
        orderitem.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void AssignTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignTaskButtonActionPerformed
        Assign_Task task = new Assign_Task();
        task.setVisible(true);
        
        // Close the current Employee UI
        this.dispose();
    }//GEN-LAST:event_AssignTaskButtonActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Sales_Order SalesOrderBack = new Sales_Order();
        SalesOrderBack.setVisible(true);
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void employeePage6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePage6ActionPerformed
        // TODO add your handling code here:
        Employee employee = new Employee();
        employee.setVisible(true);

        // Close the current Employee UI
        this.dispose();
    }//GEN-LAST:event_employeePage6ActionPerformed

    private void officeButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeButton6ActionPerformed
        // TODO add your handling code here:
        Office goToOffice = new Office();
        goToOffice.setVisible(true);

        // Close the current Employee UI
        this.dispose();
    }//GEN-LAST:event_officeButton6ActionPerformed

    private void PurchaseOrderButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseOrderButton6ActionPerformed
        Purchase_Order PO_Back = new Purchase_Order();
        PO_Back.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_PurchaseOrderButton6ActionPerformed

    private void WorksOnButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorksOnButton6ActionPerformed
        Works_On WorksOnBack = new Works_On();
        WorksOnBack.setVisible(true);
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_WorksOnButton6ActionPerformed

    private void CustomerButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButton6ActionPerformed
         Customer customer = new Customer();
        customer.setVisible(true);
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerButton6ActionPerformed

    private void BacktoInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoInsert2ActionPerformed
        // Create an instance of EmployeeTable and display it
        Works_On works_On = new Works_On();
        works_On.setVisible(true);

        // Close the current Employee UI
        this.dispose();
    }//GEN-LAST:event_BacktoInsert2ActionPerformed

    
    private void populateWorksOnTable() {
        Works_OnShowTable wTableShow = new Works_OnShowTable();
        JTable wTable = new JTable(wTableShow.getWorksOnTableModel());
        
        // Set the JTable as the view for jScrollPane1EmployeeTableShow
        jScrollPane1EmployeeTableShow2.setViewportView(wTable);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Works_On_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Works_On_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Works_On_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Works_On_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Works_On_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignTaskButton;
    private javax.swing.JButton BacktoInsert2;
    private javax.swing.JButton CustomerButton6;
    private javax.swing.JButton PurchaseOrderButton6;
    private javax.swing.JButton WorksOnButton6;
    private javax.swing.JButton employeePage6;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1EmployeeTableShow2;
    private javax.swing.JButton officeButton6;
    // End of variables declaration//GEN-END:variables
}
